### ISSUE TITLE
Object spawner

### ISSUE THREAD

**Issue by Blackbirdds** [Jacob-Mango/DayZ-CommunityOnlineTools#166]
Hello to object spawner seems to put all items which are spawned in inventory of eachother (pants will go in pants) If you try to spawn a gun u can only spawn 1 and then u need to move the cursor before u can spawn a new one again. Also when spawning items on cursor they go straight in the inventory of other players. 
Hope u can fix this issue asap

**Comment by Shivacho** [comment]
same here

**Comment by Peckerplace** [comment]
When will this be fixed? Objects are spawning in weird places. Admin info key spawn in the inventory of the vehicle I was trying to get info on. Spawn three flag poles (because they were not showing up on cursor) and found them clear across the map on the BM trader AI, actually a player found them when at the BM and could not access the AI. Any time line as to when this issue will be rectified?
